apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: nginx-obj-create # A Deployment named nginx-deployment is created, indicated by the .metadata.name field.
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9   # image and version
    ports:
    - containerPort: 80 # Open port 80 so that the container can send and accept traffic
